### ISSUE TITLE
Curious about licensing from Songoda

### ISSUE THREAD

**Issue by nikolqy** [songoda/SongodaCore#23]
A lot of plugins from Songoda here seem to be labelled as Copyright, which claims it forbids the action of reselling etc., but all Bukkit plugins must abide by the Bukkit license (GPL 3.0) as states in section C.
```
You may convey a work based on the Program, or the modifications to
produce it from the Program, in the form of source code under the
terms of section 4, provided that you also meet all of these conditions:

```
    a) The work must carry prominent notices stating that you modified
    it, and giving a relevant date.

    b) The work must carry prominent notices stating that it is
    released under this License and any conditions added under section
    7.  This requirement modifies the requirement in section 4 to
    "keep intact all notices".

    c) You must license the entire work, as a whole, under this
    License to anyone who comes into possession of a copy.  This
    License will therefore apply, along with any applicable section 7
    additional terms, to the whole of the work, and all its parts,
    regardless of how they are packaged.  This License gives no
    permission to license the work in any other way, but it does not
    invalidate such permission if you have separately received it.

    d) If the work has interactive user interfaces, each must display
    Appropriate Legal Notices; however, if the Program has interactive
    interfaces that do not display Appropriate Legal Notices, your
    work need not make them do so."

So, my question is, am I correct, that all plugins based off of Bukkit are in fact legally under the GPL v3.0 license, or is there something I'm missing?

P.S. I'm just wondering out of curiosity, don't worry, I have absolutely no intention to redistribute any Songoda plugin(s).

**Comment by SpraxDev** [comment]
> Disclaimer: I am not a lawyer and I primarily know the copyright law in Germany/European Union


Bukkit is licensed under the *GNU General Public License (v3)* I found at https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/LICENCE.txt (as you already said). *CraftBukkit* and *Spigot* do not have a `LICENSE.txt`.


To my understanding it allows commercial use, distribution, modification and private use of the licensed material (*Bukkit*).
But under the conditions that you state changes and disclose the source under the same license.

The license itself only applies to Bukkit. So if we were to create our own fork of Bukkit/Spigot (e.g. Paper-Spigot), we'd need to make sure we comply with the *GNU GPLv3*.
=> Because a Bukkit/Spigot plugin is only using the already existing and provided API, we do not need to comply with Bukkit's license.

Let me know what you think ^^
Maybe I forgot something?

**Comment by MWHunter** [comment]
This is incorrect.  You are creative a derivative work of bukkit when typing "extends JavaPlugin"

https://www.gnu.org/licenses/gpl-faq.en.html#OOPLang

and this derivative work must be licensed under a GPL compatible license unless you have received permission from every contributor of bukkit to use another license.

found this issue when trying to find if there was issues with 1.19.4 support
